version: '3'

networks:
  web:
    external: true
  internal:
    external: false
  
services:
  filetest1:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/filetest1
    ports:
      - 8000:8000